
server:
  port: 8083

spring:
  application:
    name: gateway-service  #应用名称
  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true   #??????
#          lower-case-service-id: true
#      routes:   # ????????
#        - id: user-service   # ??id
#          order: 1      #???
#          predicates:   #????
#            - Path=/api/v1/users/**
#          uri: lb://user-service   #??url
#          filters:
#            - StripPrefix=2
#        - id: content-service
#          order: 1
#          predicates:
#            - Path=/api/v1/shares/**
#          uri: lb://content-service
#          filters:
#            - StripPrefix=2021
#        - id: advertice-service
#          order: 1
#          predicates:
#            - Path=/api/v1/advertisement/**
#          uri: lb://advertice-service
#          filters:
#            - StripPrefix=2
#        - id: notice-service
#          order: 1
#          predicates:
#            - Path=/api/v1/notices/**
#          uri: lb://notice-service
#          filters:
#            - StripPrefix=2
    nacos:         #nacos??
      discovery:
        namespace: dev  #????
        server-addr: localhost:8848   #nacos??
      #        server-addr: 139.196.153.80:8848   #nacos??
#      password: nacos
#      username: nacos
      config:
        server-addr: localhost:8848
        namespace: dev

